apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: LoadBalancer
  ports:
  - port: 8085        
    targetPort: 80  
  selector:
    app: netflix-app
